
import React from 'react'

const App = () => {
  return (
    <div className="max-padd-container">
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
      <h2>hello</h2>
    </div>
  );
}

export default App
